import AboutContent from '@/components/AboutPage/AboutContent/AboutContent';
import AboutLanding from '@/components/AboutPage/AboutLanding/AboutLanding';
import Team from '@/components/AboutPage/Team/Team';
import Head from 'next/head';

const About = () => {
  return (
    <div>
      <Head>
        <title>Renewable Resources - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutLanding />
      <AboutContent />
      <Team />
    </div>
  );
};
export default About;
