import ContactForm from '@/components/ContactPage/ContactForm/ContactForm';
import ContactLanding from '@/components/ContactPage/ContactLanding/ContactLanding';
import Head from 'next/head';

const Contact = () => {
  return (
    <div>
      <Head>
        <title>Renewable Resources - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactLanding />
      <ContactForm />
    </div>
  );
};
export default Contact;
