import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import HeroSection from '@/components/HeroSection/HeroSection';
import CardSection from '@/components/CardSection/CardSection';
import { useState } from 'react';
import { useEffect } from 'react';
import MakeDonation from '@/components/MakeDonation/MakeDonation';
import Info from '@/components/Info/Info';
import Solutions from '@/components/Solutions/Solutions';

export default function Home() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);
  return (
    <>
      {mounted && (
        <>
          <Head>
            <title>Renewable Resources - Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <HeroSection />
            <CardSection />
            <MakeDonation />
            <Info />
            <Solutions />
          </main>
        </>
      )}
    </>
  );
}
